version: "3.7"

services:
  nest-app:
    image: application/nest-app
    container_name: nest-app
    build:
      dockerfile: "./Dockerfile"
      context: .
      args:
        APP_ENV: "prod"
    volumes: 
      - ./src:/app/src
    env_file: 
      - .env
    depends_on:
      - db-app
    networks: 
      - dd-network
    ports:
      - "3000:3000"
  db-app:
    image: mysql:8.0
    container_name: db-app
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
      - dd-network
    ports:
      - "3388:3306"
    environment:
      MYSQL_DATABASE: "db_app"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql/data:/var/lib/mysql:rw

networks:
  dd-network:
    external: true